In [17]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

In [18]:
class SimpleCustomBatch:
    def __init__(self, data):
        transposed_data = list(zip(*data))
        self.inp = torch.stack(transposed_data[0], 0)
        self.tgt = torch.stack(transposed_data[1], 0)

    # custom memory pinning method on custom type
    def pin_memory(self):
        self.inp = self.inp.pin_memory()
        self.tgt = self.tgt.pin_memory()
        return self

def collate_wrapper(batch):
    return SimpleCustomBatch(batch)

if __name__ == "__main__":
    # creates a 10x5 tensor of range(0, 50) incrementing every right column by 1
    inps = torch.arange(50, dtype=torch.float32).view(10, 5)
    # print(inps)

    tgts = torch.arange(10 * 5, dtype=torch.float32).view(10, 5)
    # print(tgts)
    
    dataset = TensorDataset(inps, tgts) # store this in the TensorDataset Class

    # STEPS:
    # 1: take a tensor and store it
    # 2: load the tensor with a batch_size, and other parameters.
    loader = DataLoader(dataset, batch_size=2, collate_fn=collate_wrapper,
                        pin_memory=True)

    # print(help(loader))
    
    for batch_ndx, sample in enumerate(loader):
        print(sample, batch_ndx)
        # print(sample.inp.is_pinned())
        # print(sample.tgt.is_pinned())

<__main__.SimpleCustomBatch object at 0x000001B1D2EB2420> 0
<__main__.SimpleCustomBatch object at 0x000001B1D2EB2240> 1
<__main__.SimpleCustomBatch object at 0x000001B1E6D67440> 2
<__main__.SimpleCustomBatch object at 0x000001B1D2EB2420> 3
<__main__.SimpleCustomBatch object at 0x000001B1D2EB2240> 4


In [29]:
m = nn.Linear(1, 2)
print(m.weight)
print(m.bias)

input = torch.randn(2, 1)
print(input)

output = m(input)
print(output.size())
print(output)

Parameter containing:
tensor([[0.7236],
        [0.0430]], requires_grad=True)
Parameter containing:
tensor([0.8954, 0.5411], requires_grad=True)
tensor([[ 1.0322],
        [-0.6515]])
torch.Size([2, 2])
tensor([[1.6422, 0.5856],
        [0.4239, 0.5131]], grad_fn=<AddmmBackward0>)


In [5]:
class FinancialTransformer(nn.Module):
    def _init_(self, param):
        super(FinancialTransformer, self)._init_ # we import the nn.Module methods into the class
        self.embedding = nn.Linear(1, 2)
        # self.positional_encoder = nn.Embedding(20, )
        

In [15]:
embedding = nn.Embedding(10, 3)
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
print(input, input.size())
embed = embedding(input)
print(embed, embed.size())

tensor([[1, 2, 4, 5],
        [4, 3, 2, 9]]) torch.Size([2, 4])
tensor([[[-0.5620, -0.0164,  0.8274],
         [-1.1133, -0.9781,  0.4610],
         [ 1.6398,  0.4853,  1.1278],
         [ 0.9104, -0.4623,  1.5287]],

        [[ 1.6398,  0.4853,  1.1278],
         [-0.4503, -1.1623,  0.4724],
         [-1.1133, -0.9781,  0.4610],
         [-0.1699,  1.8437, -0.1671]]], grad_fn=<EmbeddingBackward0>) torch.Size([2, 4, 3])
